// Generated by https://quicktype.io

export interface iBusinessPartnerAPI {
    id?:                    number;
    accountid?:             string;
    description?:           string;
    enabled?:               number;
    mcountry?:              string;
    mstate?:                string;
    rateMultiplier?:        number;
    scountry?:              string;
    sstate?:                string;
    type?:                  number;
    attributes?:            iAttributeAPI[];
    chargeCodes?:           iChargeCodeAPI[];
    notes?:                 any[];
    scripts?:               any[];
    itemStorageCharges?:    iItemStorageChargeAPI[];
    autoChargeCodes?:       any[];
    shippingPreDefTitles?:  iPreDefTitles;
    receivingPreDefTitles?: iPreDefTitles;
    workOrderPreDefTitles?: iPreDefTitles;
    shipmentPreDefTitles?:  iShipmentPreDefTitlesAPI;
    defaultBillings?:       iDefaultBillingAPI[];
    events?:                Event[];
    nmfcCodes?:             any[];
    scriptMaps?:            any[];
    attributeMaps?:         any[];
    monthlyBillings?:       any[];
    carrierFees?:           any[];
    files?:                 any[];
    rateMultipliers?:       any[];
    serviceLanes?:          any[];
    carrierRoutes?:         any[];
    proSettings?:           any[];
}

export interface iAttributeAPI {
    id?:                number;
    businessPartnerId?: number;
    attribute?:         number;
    ival?:              number;
    dval?:              number;
    sval?:              string;
    aval?:              any[];
}

export interface iChargeCodeAPI {
    id?:                number;
    code:               string;
    type:               number;
    businessPartnerId?: number;
    description:        string;
    rate?:              number;
    visibleOnScanner?:  number;
    minCharge?:         number;
    maxCharge?:         number;
    autoApply?:         number;
    valueFrom?:         number;
    valueTo?:           number;
    rateAssoc?:         number;
    glCode?:            string;
}

export interface iDefaultBillingAPI {
    id?:          number;
    bpId?:        number;
    uomType?:     number;
    invoiceType?: number;
    chargeRefId?: number;
    chargeType?:  number;
    itemType?:    number;
}

// export interface iEventAPI {
//     id?:             number;
//     eventType?:      number;
//     eventClass?:     number;
//     eventClassType?: number;
//     userid?:        UseridAPI;
//     dtEnd?:          string;
//     sval?:           string;
// }

// export enum UseridAPI {
   
// } 

export interface iItemStorageChargeAPI {
    id?:                  number;
    vendorId?:            number;
    description?:         string;
    type?:                number;
    rateAssoc?:           number;
    rate?:                number;
    minChg?:              number;
    glcode?:              string;
    chargeClass?:         number;
    valFrom?:             number;
    valTo?:               number;
    billingScheduleType?: number;
    billingSchedules?:    iBillingScheduleAPI[];
}

export interface iBillingScheduleAPI {
    id?:      number;
    rate?:    number;
    valFrom?: number;
    valTo?:   number;
}

export interface iPreDefTitles {
    id?:       number;
    vendorId?: number;
    type?:     number;
}

export interface iShipmentPreDefTitlesAPI {
    id?:       number;
    vendorId?: number;
}
