// Generated by https://quicktype.io

import { iVendorAPI } from "./iStorageLocationAPI";

export interface iItemAPI {
    id?:                         number;
    enabled?:                    number;
    type?:                       number;
    category?:                   number;
    itemCode?:                   string;
    description?:                string;
    valuePerEach?:               number;
    pickStyle?:                  number;
    pickOffset?:                 number;
    cycleCountEnable?:           number;
    cycleCountStyle?:            number;
    orderFreq?:                  number;
    trackingStyleEnable?:        number;
    trackingStyleSn?:            number;
    si?:                         string;
    tempRangeMax?:               number;
    tempRangeMin?:               number;
    // trackAdvFv0?:                number;
    // trackAdvFv1?:                number;
    // trackAdvFv2?:                number;
    // trackAdvFv3?:                number;
    // trackAdvFv4?:                number;
    // trackAdvFv5?:                number;
    // trackAdvFv6?:                number;
    // trackAdvFv7?:                number;
    // trackAdvFv8?:                number;
    // trackAdvFv9?:                number;
    // trackAdvFv0ModeShip?:        number;
    // trackAdvFv1ModeShip?:        number;
    // trackAdvFv2ModeShip?:        number;
    // trackAdvFv3ModeShip?:        number;
    // trackAdvFv4ModeShip?:        number;
    // trackAdvFv5ModeShip?:        number;
    // trackAdvFv6ModeShip?:        number;
    // trackAdvFv7ModeShip?:        number;
    // trackAdvFv8ModeShip?:        number;
    // trackAdvFv9ModeShip?:        number;
    // trackAdvFv0ModeRecv?:        number;
    // trackAdvFv1ModeRecv?:        number;
    // trackAdvFv2ModeRecv?:        number;
    // trackAdvFv3ModeRecv?:        number;
    // trackAdvFv4ModeRecv?:        number;
    // trackAdvFv5ModeRecv?:        number;
    // trackAdvFv6ModeRecv?:        number;
    // trackAdvFv7ModeRecv?:        number;
    // trackAdvFv8ModeRecv?:        number;
    // trackAdvFv9ModeRecv?:        number;
    // trackingStyleContainer?:     number;
    // trackingStyleExpdate?:       number;
    // trackingStyleLot?:           number;
    // trackingStyleQuaranReldate?: number;
    // trackingStyleSnReverse?:     number;
    // trackingStyleUserdef?:       number;
    // trackingStyleWeight?:        number;
    vendorId?:                   number;
    uomId?:                      number;
    uom?:                        iUOMAPI;
    kitSubItems?:                any[];
    upcs?:                       iUPCAPI[];
    itemWarehouses?:             any[];
    replenishmentPlans?:         any[];
    // vendorBrief?:                File;
    // userDefined?:                iUserDefined;
    buildable?:                  number;
    file?:                       File;
    vendor?:                     iVendorAPI;
    aliases?:                    any[];
    events?:                     Event[];
    storageLocations?:           any[];
    // nmfcCode?:                   File;
    // hazmat?:                     File;
    // storageCharge?:              iStorageCharge;
    // inboundStorage?:             File;
    // inboundHandling?:            File;
    // outboundShipping?:           File;
}
export interface iUPCAPI {
    id?: number,
    lotCode?: string,
    sublotCode?: string,
    upc: string,
    itemDescription: string,
    itemId?: number,
}

export interface iEventAPI {
    id?:             number;
    eventType?:      number;
    eventClass?:     number;
    eventClassType?: number;
    userid?:         UseridAPI;
    dtEnd?:          string;
    sval?:           string;
}

export enum UseridAPI {
    
}

export interface iFileAPI {
}

export interface iStorageChargeAPI {
    ibillingSchedulesAPI?: any[];
}

export interface iUOMAPI {
    id?:                   number;
    caseAbbrev?:           string;
    caseDepth?:            number;
    caseDescription?:      string;
    caseHasInnerpack?:     number;
    caseHeight?:           number;
    caseMaxStackWeight?:   number;
    caseTare?:             number;
    caseWeight?:           number;
    caseWidth?:            number;
    defaultOuom?:          number;
    eaAbbrev?:             string;
    eaCaseQty?:            number;
    eaDepth?:              number;
    eaDescription?:        string;
    eaHeight?:             number;
    eaTare?:               number;
    eaWeight?:             number;
    eaWidth?:              number;
    ipAbbrev?:             string;
    ipCaseQty?:            number;
    ipDepth?:              number;
    ipDescription?:        string;
    ipHeight?:             number;
    ipTare?:               number;
    ipWeight?:             number;
    ipWidth?:              number;
    itemId?:               number;
    palletAbbrev?:         string;
    palletDepth?:          number;
    palletDescription?:    string;
    palletHeight?:         number;
    palletHigh?:           number;
    palletMaxStackWeight?: number;
    palletTare?:           number;
    palletTie?:            number;
    palletWeight?:         number;
    palletWidth?:          number;
    si?:                   string;
    style?:                number;
    vendorId?:             number;
}
export interface iIventoryAdjustmentAPI {
    itemId: number,
    status: number,
    qty: number,
    lot?: string,
    storageId: number,
    lpn?: string,
    sublot?: string
}
// export interface iUserDefined {
//     id?:     number;
//     itemId?: number;
//     ft0?:    string;
//     fv0?:    string;
//     ft1?:    string;
//     fv1?:    string;
//     ft2?:    string;
//     fv2?:    string;
//     ft3?:    string;
//     fv3?:    string;
//     ft4?:    string;
//     fv4?:    string;
//     ft5?:    string;
//     fv5?:    string;
//     ft6?:    string;
//     fv6?:    string;
//     ft7?:    string;
//     fv7?:    string;
//     ft8?:    string;
//     fv8?:    string;
//     ft9?:    string;
//     fv9?:    string;
// }


// export interface iVendorAPI {
//     id?:                    number;
//     accountid?:             string;
//     description?:           string;
//     enabled?:               number;
    // mcountry?:              string;
    // mstate?:                string;
    // rateMultiplier?:        number;
    // scountry?:              string;
    // sstate?:                string;
    // type?:                  number;
    // attributes?:            iAttribute[];
    // chargeCodes?:           iChargeCode[];
    // notes?:                 any[];
    // scripts?:               any[];
    // itemStorageCharges?:    iItemStorageCharge[];
    // autoChargeCodes?:       any[];
    // shippingPreDefTitles?:  iPreDefTitles;
    // receivingPreDefTitles?: iPreDefTitles;
    // workOrderPreDefTitles?: iPreDefTitles;
    // shipmentPreDefTitles?:  iShipmentPreDefTitles;
    // defaultBillings?:       iDefaultBilling[];
    // events?:                Event[];
    // nmfcCodes?:             any[];
    // scriptMaps?:            any[];
    // attributeMaps?:         any[];
    // monthlyBillings?:       any[];
    // carrierFees?:           any[];
    // files?:                 any[];
    // rateMultipliers?:       any[];
    // serviceLanes?:          any[];
    // carrierRoutes?:         any[];
    // proSettings?:           any[];
// }

// export interface iAttribute {
//     id?:                number;
//     businessPartnerId?: number;
//     attribute?:         number;
//     ival?:              number;
//     dval?:              number;
//     sval?:              string;
//     aval?:              any[];
// }

// export interface iChargeCode {
//     id?:                number;
//     code?:              string;
//     type?:              number;
//     businessPartnerId?: number;
//     description?:       string;
//     rate?:              number;
//     visibleOnScanner?:  number;
//     minCharge?:         number;
//     maxCharge?:         number;
//     autoApply?:         number;
// }

// export interface iDefaultBilling {
//     id?:          number;
//     bpId?:        number;
//     uomType?:     number;
//     invoiceType?: number;
//     chargeRefId?: number;
//     chargeType?:  number;
//     itemType?:    number;
// }

// export interface iItemStorageCharge {
//     id?:                  number;
//     vendorId?:            number;
//     description?:         string;
//     type?:                number;
//     rateAssoc?:           number;
//     rate?:                number;
//     minChg?:              number;
//     glcode?:              string;
//     chargeClass?:         number;
//     valFrom?:             number;
//     valTo?:               number;
//     billingScheduleType?: number;
//     billingSchedules?:    iBillingSchedule[];
// }

// export interface iBillingSchedule {
//     id?:      number;
//     rate?:    number;
//     valFrom?: number;
//     valTo?:   number;
// }

// export interface iPreDefTitles {
//     id?:       number;
//     vendorId?: number;
//     type?:     number;
// }

// export interface iShipmentPreDefTitles {
//     id?:       number;
//     vendorId?: number;
// }
