// Generated by https://quicktype.io

export interface iUser {
    id?:                  number;
    description?:         string;
    dialect?:             number;
    email?:               string;
    enabled?:             number;
    lastPwdchangeDt?:     string;
    loginErrors?:         number;
    status?:              number;
    type?:                number;
    userid?:              string;
    userGrpId?:           number;
    group?:               Group;
    warehouses?:          Warehouse[];
    attributes?:          Attribute[];
    businessPartners?:    BusinessPartner[];
    forcedPasswordReset?: number;
    events?:              Event[];
}

export interface Attribute {
    id?:        number;
    userId?:    number;
    attribute?: number;
    ival?:      number;
    sval?:      string;
    dval?:      number;
}

export interface BusinessPartner {
    id?:     number;
    userId?: number;
    bpId?:   number;
}


export interface Event {
    id?:             number;
    eventType?:      number;
    eventClass?:     number;
    eventClassType?: number;
    userid?:         string;
    dtEnd?:          string;
    sval?:           string, //Sval;
    ival?:          number;
}

// export enum Sval {
//     ChangedPassword = "Changed password",
//     CompletedTutorial = "Completed Tutorial",
//     Create = "Create",
//     Edit = "Edit",
//     EditUserGrp = "EDIT USER GRP",
//     LogOff = "Log off",
//     LogOnIP181115210224 = "Log on (IP - 181.115.210.224)",
//     LogOnIP18111521025 = "Log on (IP - 181.115.210.25)",
//     LogOnIP18612119570 = "Log on (IP - 186.121.195.70)",
//     LogOnIP5415152146 = "Log on (IP - 54.151.52.146)",
// }

export interface Group {
    id?:                 number;
    category?:           number;
    guest?:              number;
    enabled?:            number;
    description?:        string;
    events?:             Event[];
    securityAttributes?: SecurityAttribute[];
}

export interface SecurityAttribute {
    id?:        number;
    attribute?: number;
    ival?:      number;
    grpId?:     number;
}

export interface Warehouse {
    id?:          number;
    userId?:      number;
    warehouseId?: number;
}
