// Generated by https://quicktype.io

export enum SequenceTypes {
    UserDefined= 1,
    ProNumber = 6,
    LPN = 4,
    VICS = 2,
    WDGInternalSequence = 9,
}

export interface SequenceAPI {
    id?:           number;
    Sequence:         string;
    Type:         SequenceTypes;
    Value: number;
}
