// Generated by https://quicktype.io


export interface UserGroupAPI {
    id?:                 number;
    category?:           number;
    guest?:              number;
    enabled?:            boolean;
    description:        string;
    // events?:             UserGroupEvent[];
    securityAttributes?: UserGroupSecurityAttribute[];
}

// export interface UserGroupEvent {
//     id:             number;
//     warehouseId:    number;
//     eventType:      number;
//     eventClass:     number;
//     eventClassType: number;
//     userid:         string;
//     dtEnd:          string;
//     ival:           number;
//     itype:          number;
//     sval:           string;
//     idur:           number;
// }

export interface UserGroupSecurityAttribute {
    id:        number;
    attribute: number;
    ival:      number;
    grpId:     number;
}
