// Generated by https://quicktype.io

export interface iWarehouseAPI {
    id?:               number;
    enabled?:          number;
    category?:         number;
    description?:      string;
    address1?:         string;
    address2?:         string;
    city?:             string;
    state?:            string;
    zip?:              string;
    country?:          string;
    adminName?:        string;
    adminPhone?:       string;
    adminEmail?:       string;
    opdayMon?:         number;
    opdayTue?:         number;
    opdayWed?:         number;
    opdayThu?:         number;
    opdayFri?:         number;
    opdaySat?:         number;
    opdaySun?:         number;
    bonded?:           number; //mandatory for the system not for the User
    mode?:             number; //mandatory for the system not for the User
    lockedCreate?:     number; //mandatory for the system not for the User
    clazz?:            string; 
    nlIP?:             string; 
    nlPort?:           string;
    nlLabelDirectory?: string;
    invoiceSequence?:  string;
    printGuid?:        string; //mandatory for the system not for the User
}
