// Generated by https://quicktype.io

import { UserGroupAPI } from "../userGroup";

export interface UserAPI {
    id?:                       number;
    description:              string;
    dialect?:                  number;
    email:                    string;
    enabled?:                  boolean;
    lastPwdchangeDt?:          string;
    loginErrors?:              number;
    mphone?:                   string;
    pager?:                    string;
    password:                 string;
    phone?:                    string;
    printerDefDocDriver?:      string;
    printerDefDocPort?:        string;
    printerDefDocPrinter?:     string;
    printerDefLabelDriver?:    string;
    printerDefLabelPort?:      string;
    printerDefLabelPrinter?:   string;
    printerDefSpLabelDriver?:  string;
    printerDefSpLabelPort?:    string;
    printerDefSpLabelPrinter?: string;
    shipmentId?:               number;
    status?:                   number;
    type?:                     number;
    userid?:                   string;
    warehouseId?:              number;
    userGrpId?:                number;
    pwd0?:                     string;
    pwd1?:                     string;
    pwd2?:                     string;
    pwd3?:                     string;
    pwd4?:                     string;
    pwd5?:                     string;
    pwd6?:                     string;
    pwd7?:                     string;
    pwd8?:                     string;
    pwd9?:                     string;
    group?:                    UserGroupAPI;
    warehouses?:               UserWarehouseAPI[];
    attributes?:               UserAttributeAPI[];
    businessPartners?:         BusinessPartner[];
    forcedPasswordReset?:      boolean;
    events?:                   Event[];
}

export interface UserAttributeAPI {
    id?:        number;
    userId?:    number;
    attribute?: number;
    ival?:      number;
    sval?:      string;
    dval?:      number;
}

export interface BusinessPartner {
    id?:     number;
    userId?: number;
    bpId?:   number;
}

// export interface UserEventAPI {
//     id?:             number;
//     warehouseId?:    number;
//     eventType?:      number;
//     eventClass?:     number;
//     eventClassType?: number;
//     userid?:         string;
//     dtEnd?:          string;
//     ival?:           number;
//     itype?:          number;
//     sval?:           string;
//     idur?:           number;
// }

// export interface UserGroupAPI {
//     id?:                 number;
//     category?:           number;
//     guest?:              number;
//     enabled?:            boolean;
//     description?:        string;
//     events?:             UserEventAPI[];
//     securityAttributes?: UserSecurityAttributeAPI[];
// }

export interface UserSecurityAttributeAPI {
    id?:        number;
    attribute?: number;
    ival?:      number;
    grpId?:     number;
}

export interface UserWarehouseAPI {
    id?:          number;
    userId?:      number;
    warehouseId?: number;
}
